AIRDASHER/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('HomePage.urls')),
    path('RouteDev/', include('RouteDev.urls')),
    path('NewAirports/', include('NewAirports.urls')),
    path('GeneralStats/', include('GeneralStats.urls')),
    path('About/', include('About.urls')),
    path('admin/', admin.site.urls),
]

About/urls.py
from django.urls import path

from . import views

app_name = "About"
urlpatterns = [
    path('', views.About, name='About'),
]

GeneralStats/urls.py
from django.urls import path

from . import views

app_name = "GeneralStats"
urlpatterns = [
    path('', views.GeneralStats, name = 'GeneralStats'),
]

HomePage/urls.py
from django.urls import path

from . import views

app_name = "HomePage"
urlpatterns = [
    path('', views.HomePage, name='HomePage'),
]

NewAirports/urls.py
from django.urls import path

from . import views

app_name = "NewAirports"
urlpatterns = [
    path('', views.NewAirports, name = 'NewAirports'),
]

RouteDev/urls.py
from django.urls import path

from . import views

app_name = "RouteDev"
urlpatterns = [
    path('', views.RouteDevHome, name = 'RouteDevHome'),
    path('CitySelection', views.CitySelection, name='CitySelection'),
    path('RouteSelection', views.RouteSelection, name='RouteSelection'),
    path('CostResourceAnalysis', views.CostResourceAnalysis, name='CostResourceAnalysis'),
]

HomePage/views.py
from django.shortcuts import render

def HomePage(request):
    return render(request, 'HomePage/HomePage.html')

HomePage/templates/HomePage/HomePage.html
{% load static %}

<DOCTYPE html>
<html>

    <head>
        <title>Home Page</title>
        <link rel="stylesheet" href="{% static 'HomePage/colors.css' %}">
        <link rel="stylesheet" href="{% static 'HomePage/HomePage.css' %}">
    </head>

    <body>
        <div id="all-window">
            <div id="header">
                <div id="header-title">
                    <img src="{% static 'HomePage/HomePage_Pics/logo.png' %}" alt="AIRDASHER logo">
                    <h1>AIRDASHER</h1>
                </div>
                <div id="header-info">
                    <div id="header-info-content">
                        <h3>ANALYTICAL INTELLIGENCE FOR ROUTE DEVELOPMENT AND STRATEGIC HANDLING OF ECONOMIC RESOURCES</h3>
                        <a title="Know more about AIRDASHER" href="{% url 'About:About' %}">
                            <img src="{% static 'HomePage/HomePage_Pics/info.png' %}" alt="Info logo">
                        </a>
                    </div>
                </div>
            </div>
            <div id="cards">
                <div class="card" id="routedev-card">
                    <a href="{% url 'RouteDev:RouteDevHome' %}">
                        <div class="card-content">
                            <div class="card-img">
                                <img src="{% static 'HomePage/HomePage_Pics/RouteDev.jpg' %}" alt="Route Development">
                            </div>
                            <div class="card-header">
                                <div class="card-title">
                                    <h1>ANALYZE NEW<br>ROUTES</h1>    
                                </div>
                                <div class="card-info">
                                    <h3>Integrate high-demand & high-growth cities into your airline's network by developing new routes. Perform a parameterized cost & resource analysis to judge the route's feasibility & profitability.</h3>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="card" id="airport-card">
                    <a href="{% url 'NewAirports:NewAirports' %}">
                        <div class="card-content">
                            <div class="card-img">
                                <img src="{% static 'HomePage/HomePage_Pics/Airport.jpg' %}" alt="Route Development">
                            </div>
                            <div class="card-header">
                                <div class="card-title">
                                    <h1>ANALYZE NEW<br>AIRPORTS</h1>    
                                </div>
                                <div class="card-info">
                                    <h3>Identify Indian tier-I/II cities which have high enough demand and growth in air travel to consider setting up a new airport. Get a detailed view of how & why demand is expected to grow for such new airport candidates.</h3>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="card" id="generalstats-card">
                    <a href="{% url 'GeneralStats:GeneralStats' %}">
                        <div class="card-content">
                            <div class="card-img">
                                <img src="{% static 'HomePage/HomePage_Pics/GeneralStats.jpg' %}" alt="Route Development">
                            </div>
                            <div class="card-header">
                                <div class="card-title">
                                    <h1>GENERAL<br>STATISTICS</h1>    
                                </div>
                                <div class="card-info">
                                    <h3>Know about different insights & statistics which can be obtained from our manually-built high-quality real dataset of Indian & APAC flight connectivity. Know trends in aircraft type & city-to-city connectivity.</h3>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </body>

</html>