AIRDASHER/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('HomePage.urls')),
    path('RouteDev/', include('RouteDev.urls')),
    path('NewAirports/', include('NewAirports.urls')),
    path('GeneralStats/', include('GeneralStats.urls')),
    path('About/', include('About.urls')),
    path('admin/', admin.site.urls),
]

About/urls.py
from django.urls import path

from . import views

app_name = "About"
urlpatterns = [
    path('', views.About, name='About'),
]

HomePage/urls.py
from django.urls import path

from . import views

app_name = "HomePage"
urlpatterns = [
    path('', views.HomePage, name='HomePage'),
]

RouteDev/urls.py
from django.urls import path

from . import views

app_name = "RouteDev"
urlpatterns = [
    path('', views.RouteDevHome, name = 'RouteDevHome'),
    path('CitySelection', views.CitySelection, name='CitySelection'),
    path('RouteSelection', views.RouteSelection, name='RouteSelection'),
    path('CostResourceAnalysis', views.CostResourceAnalysis, name='CostResourceAnalysis'),
]

RouteDev/models.py
from django.db import models

class GENERAL_PARAMS_CLASS(models.Model):
    FORECAST_YEAR = models.IntegerField(default = 2033)
    PRESENT_YEAR = models.IntegerField(default = 2023)
    CAPACITY_NARROWBODY = models.IntegerField(default = 300)
    CAPACITY_TURBOPROP = models.IntegerField(default = 100)
    FLEET_NARROWBODY = models.IntegerField(default = 5)
    FLEET_TURBOPROP = models.IntegerField(default = 5)
    INFLATION_RATE = models.FloatField(default = 7.0)
    FIXED_COST = models.IntegerField()
    OPERATING_COST = models.IntegerField()
    OTHER_COST = models.IntegerField()
    MIN_PROFIT_MARGIN = models.FloatField(default = 0)
    ANALYSIS_POINTS = models.CharField(max_length = 200)
    SAMPLE_NAME = models.CharField(max_length = 20)
    ONLY_HUBS = models.BooleanField(default = True)
    DEMAND_FULFILMENT_RATE = models.FloatField(default = 100.0)

class CITY_CLASS(models.Model):
    NAME = models.CharField(max_length = 30)
    SHORTENED_NAME = models.CharField(max_length = 15, default = '')
    INFO = models.CharField(max_length = 100, default = '')
    AIRPORT_NAME = models.CharField(max_length = 3)
    GROWTH_RATE = models.FloatField()
    FORECASTED_DEMAND = models.IntegerField()
    TOURISM_GROWTH = models.IntegerField()
    ECONOMIC_GROWTH = models.IntegerField()
    EDUCATION_GROWTH = models.IntegerField()
    POPULATION_GROWTH = models.IntegerField()
    LATITUDE = models.FloatField()
    LONGITUDE = models.FloatField()
    SELECTED = models.BooleanField(default = False)

    def __str__(self):
        return self.NAME

class AIRPORT_CLASS(models.Model):
    NAME = models.CharField(max_length = 30)
    SHORTENED_NAME = models.CharField(max_length = 15, default = '')
    AIRPORT_NAME = models.CharField(max_length = 3)
    IS_HUB = models.BooleanField(default = False)
    LATITUDE = models.FloatField()
    LONGITUDE = models.FloatField()

    def __str__(self):
        return self.NAME

class CONNECTION_CLASS(models.Model):
    NODE1 = models.ForeignKey(AIRPORT_CLASS, on_delete = models.CASCADE, related_name = 'node1', null = True)
    NODE2 = models.ForeignKey(AIRPORT_CLASS, on_delete = models.CASCADE, related_name = 'node2', null = True)
    TWO_WAY_FLIGHT = models.BooleanField(default = False)

class ROUTE_CLASS(models.Model):
    CITY = models.ForeignKey(CITY_CLASS, on_delete = models.CASCADE, related_name = 'to_city', null = True)
    AIRPORT = models.ForeignKey(AIRPORT_CLASS, on_delete = models.CASCADE, related_name = 'from_city', null = True)
    DURATION_IN = models.IntegerField()
    DURATION_OUT = models.IntegerField()
    DURATION = models.IntegerField(default = 0)
    RAILWAYS_NUM = models.IntegerField(default = 0)
    RAILWAYS_DURATION = models.CharField(default = '', max_length = 10)
    RAILWAYS_CAPACITY = models.CharField(default = '', max_length = 10)
    DISTANCE = models.IntegerField()
    PRESENT_DEMAND_IN = models.IntegerField()
    PRESENT_DEMAND_OUT = models.IntegerField()
    FORECASTED_DEMAND_IN = models.IntegerField()
    FORECASTED_DEMAND_OUT = models.IntegerField()
    GROWTH_IN = models.FloatField()
    GROWTH_OUT = models.FloatField()
    GROWTH = models.FloatField()
    PRICE_IN_MARKET = models.CharField(max_length = 10)
    PRICE_OUT_MARKET = models.CharField(max_length = 10)
    NUM_IN_MARKET = models.IntegerField()
    NUM_OUT_MARKET = models.IntegerField()
    MARKET_SHARE_IN = models.FloatField(default = -1)
    MARKET_SHARE_OUT = models.FloatField(default = -1)
    SELECTED = models.BooleanField(default = False)

    def __str__(self):
        return self.CITY.NAME + "-" + self.AIRPORT.NAME

class ROUTE_PARAMS_CLASS(models.Model):
    PRICE_IN = models.IntegerField()
    PRICE_OUT = models.IntegerField()
    ROUTE = models.ForeignKey(ROUTE_CLASS, on_delete = models.SET_NULL, null = True)

class OPTION_CLASS(models.Model):
    FEASIBILITY = models.BooleanField(default = False)
    NUM_PLANES = models.CharField(max_length = 200)
    ROUTE = models.ForeignKey(ROUTE_CLASS, on_delete = models.CASCADE)
    DEMAND = models.FloatField()
    CAPACITY = models.FloatField()
    EXPENSES = models.FloatField()
    EARNINGS = models.FloatField()
    PROFIT_MARGIN = models.FloatField()
    PROFITABILITY_YEAR = models.CharField(max_length = 5)
    OCCUPANCY_RATE = models.FloatField()
    RANK = models.IntegerField(default = -1)

    def __str__(self):
        return f"{self.ROUTE}-{self.NUM_PLANES}"

RouteDev/views.py
from django.shortcuts import render, redirect
from .models import GENERAL_PARAMS_CLASS, ROUTE_PARAMS_CLASS, ROUTE_CLASS, OPTION_CLASS, CITY_CLASS, AIRPORT_CLASS, CONNECTION_CLASS

import ast
from pathlib import Path
import shutil
import os

from AnalysisScripts.CitySelection import CitySelection_Script, Airport
from AnalysisScripts.RouteSelection import RouteSelection_Script
from AnalysisScripts.CostResourceAnalysis import CostResourceAnalysis_Script
from AnalysisScripts.PreProcessor import PreProcessor

# Load all tier-I/II cities
tier_1_2_cities = [
    'Ahmedabad', 'Bengaluru', 'Mumbai', 'Pune', 'Chennai', 'Hyderabad', 'Kolkata', 'Delhi', 'Visakhapatnam', 'Guwahati', 'Patna',
    'Raipur', 'Gurugram', 'Shimla', 'Jamshedpur', 'Thiruvananthapuram', 'Bhopal', 'Bhubaneswar', 'Amritsar', 'Jaipur', 'Lucknow', 'Dehradun'
]
tier_1_2_cities = tier_1_2_cities + (
    "Guntur, Kakinada, Kurnool, Nellore, Rajamahendravaram, Vijayawada".split(', ')
) + (
    "Bilaspur, Bhilai".split(', ')
) + (
    "Anand, Bhavnagar, Dahod, Jamnagar, Rajkot, Surat, Vadodara".split(', ')
) + (
    "Faridabad, Karnal".split(', ')
) + (
    "Hamirpur".split(', ')
) + (
    "Bokaro Steel City, Dhanbad, Ranchi".split(', ')
) + (
    "Belagavi, Hubballi-Dharwad, Kalaburagi, Mangaluru, Mysuru, Vijayapura".split(', ')
) + (
    "Kannur, Kochi, Kollam, Kozhikode, Malappuram, Thrissur".split(', ')
) + (
    "Gwalior, Indore, Jabalpur, Ratlam, Ujjain".split(', ')
) + (
    "Amravati, Aurangabad, Bhiwandi, Dombivli, Jalgaon, Kolhapur, Nagpur, Nanded, Nashik, Sangli, Solapur, Vasai-Virar".split(', ')
) + (
    "Cuttack, Rourkela".split(', ')
) + (
    "Jalandhar, Ludhiana".split(', ')
) + (
    "Ajmer, Bikaner, Jodhpur".split(', ')
) + (
    "Coimbatore, Erode, Madurai, Salem, Thanjavur, Tiruchirappalli, Tirunelveli, Tiruvannamalai, Vellore".split(', ')
) + (
    "Warangal".split(', ')
) + (
    "Agra, Aligarh, Bareilly, Ghaziabad, Gorakhpur, Jhansi, Kanpur, Mathura, Meerut, Moradabad, Noida, Prayagraj, Varanasi".split(', ')
) + (
    "Asansol, Berhampore, Burdwan, Durgapur, Purulia, Siliguri".split(', ')
) + (
    "Chandigarh, Jammu, Puducherry, Srinagar".split(', ')
)

# If name is too long, we shorten it to not disturb web UI
def shorten_name(name):
    if(len(name) > 12):
        return ''.join(name[:10]) + '...'
    else:
        return name

# Route Development Home Page
def RouteDevHome(request):
    return render(request, 'RouteDev/RouteDevHome.html')

# City Selection Page
def CitySelection(request):

    nothing_changed = True
    first_time = False
    sample_unchanged = True
    forecast_year_unchanged = True
    
    if(request.method == 'POST'):    # If post data sent to view, that means parameter update was made or sample was selected

        NEW_FORECAST_YEAR = int(request.POST['NEW_FORECAST_YEAR'])
        NEW_SAMPLE_NAME = request.POST['NEW_SAMPLE_NAME']
        NEW_ONLY_HUBS = request.POST['NEW_ONLY_HUBS']

        # Update ONLY_HUBS param in GENERAL_PARAMS
        general_params = GENERAL_PARAMS_CLASS.objects.all()[0]
        if(NEW_ONLY_HUBS == 'True'):
            general_params.ONLY_HUBS = True
        else:
            general_params.ONLY_HUBS = False
        general_params.save()
        
        # Check what has changed
        forecast_year_unchanged = (NEW_FORECAST_YEAR == general_params.FORECAST_YEAR)
        sample_unchanged = (NEW_SAMPLE_NAME == general_params.SAMPLE_NAME)
        nothing_changed = forecast_year_unchanged & sample_unchanged

        if(nothing_changed == False):    # If something has changed (either parameter or sample or both)
            
            # Update GENERAL_PARAMS
            general_params = GENERAL_PARAMS_CLASS.objects.all()[0]
            general_params.FORECAST_YEAR = NEW_FORECAST_YEAR
            general_params.SAMPLE_NAME = NEW_SAMPLE_NAME
            general_params.save()
    
    else:    # Else coming to the CitySelection page for the first time
        first_time = True

    if((nothing_changed == False) or (first_time == True)):    # If something has changed (either parameter or sample or both) or if entering page for the first time

        # Run CitySelection_Script
        global tier_1_2_cities
        general_params = GENERAL_PARAMS_CLASS.objects.all()[0]
        THIS_FOLDER = Path(__file__).parent.resolve()
        shutil.rmtree(f'{THIS_FOLDER}/../RouteDev/static/RouteDev/PlotlyGraphs/CitySelection/', ignore_errors = True)
        os.mkdir(f'{THIS_FOLDER}/../RouteDev/static/RouteDev/PlotlyGraphs/CitySelection/')
        preprocessor = PreProcessor(f'{THIS_FOLDER}/../AnalysisScripts/PreProcessed_Datasets')
        cities, airports = CitySelection_Script(
            general_params.__dict__,
            preprocessor, tier_1_2_cities,
            f'{THIS_FOLDER}/../RouteDev/static/RouteDev/ProcessingOutputs',
            f'{THIS_FOLDER}/../RouteDev/static/RouteDev/PlotlyGraphs/CitySelection'
        )

        # Update CITY_CLASS based on cities outputted by CitySelection_Script
        CITY_CLASS.objects.all().delete()
        for city in cities:
            city_params = cities[city]
            city_info = preprocessor.city_info[city]
            city_object = CITY_CLASS(
                NAME = city,
                SHORTENED_NAME = shorten_name(city),
                INFO = city_info,
                AIRPORT_NAME = city_params['Airport'],
                GROWTH_RATE = round(city_params['GrowthRate']),
                FORECASTED_DEMAND = city_params['PredictedFutureTraffic'],
                TOURISM_GROWTH = round(city_params['GrowthRate']),
                ECONOMIC_GROWTH = round(city_params['GrowthRate']),
                EDUCATION_GROWTH = round(city_params['GrowthRate']),
                POPULATION_GROWTH = round(city_params['GrowthRate']),
                LATITUDE = city_params['Latitude'],
                LONGITUDE = city_params['Longitude'],
            )
            city_object.save()
        
        if((sample_unchanged == False) or (len(airports) != len(AIRPORT_CLASS.objects.all()))):    # If sample network got changed

            # Update the AIRPORT_CLASS based on all airports in selected network                
            AIRPORT_CLASS.objects.all().delete()
            for airport in airports:
                airport_params = airports[airport].airport_info
                airport_object = AIRPORT_CLASS(
                    AIRPORT_NAME = airport,
                    NAME = airport_params['City/Town'],
                    SHORTENED_NAME = shorten_name(airport_params['City/Town']),
                    IS_HUB = airport_params['IsHub'],
                    LATITUDE = airport_params['Latitude'],
                    LONGITUDE = airport_params['Longitude'],
                )
                airport_object.save()

            # Update the CONNECTION_CLASS based on all routes in selected network
            CONNECTION_CLASS.objects.all().delete()
            connections_made = []
            all_airport_objects = AIRPORT_CLASS.objects.all()
            for airport1_object in all_airport_objects:
                to_airport_list = airports[airport1_object.AIRPORT_NAME].to_airport_list
                for airport2 in to_airport_list:
                    airport2_object = all_airport_objects.filter(AIRPORT_NAME = airport2.airport_info['Name'])
                    assert(len(airport2_object) == 1)
                    airport2_object = airport2_object[0]
                    connection = CONNECTION_CLASS(NODE1 = airport1_object, NODE2 = airport2_object)
                    if((airport2_object.AIRPORT_NAME, airport1_object.AIRPORT_NAME) not in connections_made):
                        connections_made.append((airport1_object.AIRPORT_NAME, airport2_object.AIRPORT_NAME))
                        connection.TWO_WAY_FLIGHT = False
                    else:
                        connection.TWO_WAY_FLIGHT = True
                    connection.save()

    # Load all required info for HTML display
    general_params = GENERAL_PARAMS_CLASS.objects.all()[0]
    cities = CITY_CLASS.objects.all()
    airports = AIRPORT_CLASS.objects.all()
    connections = CONNECTION_CLASS.objects.filter(TWO_WAY_FLIGHT = False)

    # Load plotly graphs
    divs1 = []
    divs2 = []
    THIS_FOLDER = Path(__file__).parent.resolve()
    for city in cities:
        try:
            div1 = open(f'{THIS_FOLDER}/../RouteDev/static/RouteDev/PlotlyGraphs/CitySelection/{city.NAME}_CitySelection_Graph1.txt', 'r').read()
            div2 = open(f'{THIS_FOLDER}/../RouteDev/static/RouteDev/PlotlyGraphs/CitySelection/{city.NAME}_CitySelection_Graph2.txt', 'r').read()
            divs1.append(div1)
            divs2.append(div2)
        except:
            print("PROBLEM SEEN WITH PLOTLY GRAPHS!")
            pass

    # Send required info to HTML
    context = {
        'general_params_info': general_params,
        'cities_info': cities,
        'cities_div_info': zip(cities, divs1, divs2),
        'airports_info': airports,
        'connections_info': connections
    }
    return render(request, 'RouteDev/CitySelection.html', context)

# Route Selection Page
def RouteSelection(request):

    if(request.method == 'POST'):    # If post data sent to view, that means city has been selected
        
        # Fetch city info which has been selected
        selected_city_name = [x for x in request.POST if x.startswith('SELECTED_CITY_')]
        assert(len(selected_city_name) == 1)
        selected_city_name = selected_city_name[0].split('_')[-1]

        # Fetch info about the previously selected city (if any)
        prev_selected_city = CITY_CLASS.objects.filter(SELECTED = True)
        assert(len(prev_selected_city) <= 1)
        
        # Update selected status of city
        if(len(prev_selected_city) == 1):
            prev_selected_city = prev_selected_city[0]
            prev_selected_city_name = prev_selected_city.NAME
            if(prev_selected_city_name != selected_city_name):

RouteDev/templates/RouteDev/CitySelection.html
{% load static %}

<!DOCTYPE html>
<html>
    
    <head>
        <title>City Selection</title>
        
        <!-- Leaflet JS -->
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin=""/>
        <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
        <link rel="stylesheet" href="{% static 'RouteDev/Maps/map.css' %}">

        <link rel="stylesheet" href="{% static 'HomePage/colors.css' %}">
        <link rel="stylesheet" href="{% static 'RouteDev/CitySelection/CitySelection.css' %}">
        
        <!-- Plotly JS -->
        <script src="https://cdn.plot.ly/plotly-2.18.2.min.js"></script>
    </head>
    
    <body>

        <div id="all-window">
            <div id="map-content">
                <div id="map"></div>
                <script src="{% static 'RouteDev/Maps/map.js' %}"></script>
                {% for airport in airports_info %}
                    <script>
                        MAPS_PLOT.init_coords("{{ airport.LATITUDE }},{{airport.LONGITUDE}}");
                        MAPS_PLOT.init_names("{{ airport.NAME }}");
                        MAPS_PLOT.init_airport_names("{{ airport.AIRPORT_NAME }}");
                        MAPS_PLOT.init_is_hubs("{{ airport.IS_HUB }}");
                    </script>
                {% endfor %}
                {% for connection in connections_info %}
                    <script>
                        MAPS_PLOT.init_routes(
                            "{{ connection.NODE1.LATITUDE }},{{connection.NODE1.LONGITUDE}}",
                            "{{ connection.NODE2.LATITUDE }},{{connection.NODE2.LONGITUDE}}"
                        )
                    </script>
                {% endfor %}
                {% for city in cities_info %}
                    <script>
                        MAPS_PLOT.init_city_coords("{{ city.LATITUDE }},{{city.LONGITUDE}}");
                        MAPS_PLOT.init_city_names("{{ city.NAME }}");
                    </script>
                {% endfor %}
                <script>
                    MAPS_PLOT.plot_map("{{ general_params_info.SAMPLE_NAME }}", 0, 1, 0);
                </script>
            </div>
            <div id="right-pane">
                <div id="right-pane-title">
                    <h1>HIGH-GROWTH CITIES</h1>
                </div>
                <div id="cities">
                    {% for city, div1, div2 in cities_div_info %}
                        <div id="City{{ forloop.counter }}" class="city">
                            <div class="city-title">
                                <h1>{{ city.SHORTENED_NAME }}</h1>
                            </div>
                            <div class="city-info">
                                <h3>GROWTH RATE: {{ city.GROWTH_RATE }}%</h3>
                            </div>
                        </div>
                        <div id="CityModal{{ forloop.counter }}" class="CityModal">
                            <div class="modal-content-outer">
                                <div class="close_button">
                                    <span class="close" id="close{{ forloop.counter }}">&times;</span>
                                </div>
                                <div class="modal-content">
                                    <div class="modal-content-info">
                                        <div class="modal-title">
                                            <h1>{{ city.SHORTENED_NAME }}</h1>
                                            <h3>AIRPORT: {{ city.AIRPORT_NAME }}</h3>
                                        </div>
                                        <h4>{{ city.INFO }}</h4>
                                        <h3>PASSENGER DEMAND TILL {{ general_params_info.FORECAST_YEAR }} EXPECTED TO GROW BY {{ city.GROWTH_RATE }}%</h3>
                                        <form action="{% url 'RouteDev:RouteSelection' %}" method="post" class="select-city">
                                            {% csrf_token %}
                                            <button name="SELECTED_CITY_{{ city.NAME }}">SELECT CITY</button>
                                        </form>
                                    </div>
                                    <div class="modal-content-graphs">
                                        {% autoescape off %}
                                        {{ div1 }}
                                        {{ div2 }}
                                        {% endautoescape %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <script src="{% static 'RouteDev/CitySelection/CitySelection.js' %}"></script>
                </div>
                <form action="{% url 'RouteDev:CitySelection' %}" method="post" id="params">
                    {% csrf_token %}
                    <div id="params-config">
                        <div class="param-config">
                            <label title="Select year till which forecasts are made" class="param_help">FORECAST YEAR:</label>
                            <input type="number" name="NEW_FORECAST_YEAR" id="FORECAST_YEAR" value="{{ general_params_info.FORECAST_YEAR }}" min="2025" max="2043" step="1">
                        </div>
                        <div class="param-config">
                            <label title="Select whether new routes should be made to only hubs of network or any airport" class="param_help">ROUTE TYPE:</label>
                            <select id="ONLY_HUBS" name="NEW_ONLY_HUBS">
                                <option value="False" {% if general_params_info.ONLY_HUBS == False %}selected{% endif %}>TO ANY AIRPORT</option>
                                <option value="True" {% if general_params_info.ONLY_HUBS == True %}selected{% endif %}>ONLY TO HUBS</option>
                            </select>      
                        </div>
                        <div class="param-config">
                            <label title="Select sample network to develop new routes for" class="param_help">SAMPLE:</label>
                            <select id="SAMPLE_NAME" name="NEW_SAMPLE_NAME" value="{{ general_params_info.SAMPLE_NAME }}">
                                <option value="AirAsia_India" {% if general_params_info.SAMPLE_NAME == "AirAsia_India" %}selected{% endif %}>Air Asia India</option>
                                <option value="Akasa_Air" {% if general_params_info.SAMPLE_NAME == "Akasa_Air" %}selected{% endif %}>Akasa Air</option>
                                <option value="Star_Air" {% if general_params_info.SAMPLE_NAME == "Star_Air" %}selected{% endif %}>Star Air</option>
                            </select>
                        </div>
                    </div>
                    <div id="params-submit">
                        <input type="submit" value="UPDATE">
                    </div>
                </div>
            </div>
        </div>

        <div id="back">
            <a href="{% url 'HomePage:HomePage' %}">
                <img src="{% static 'HomePage/HomePage_Pics/back.png' %}" alt="Back">
            </a>
        </div>
    
    </body>
</html>

RouteDev/templates/RouteDev/RouteDevHome.html
{% load static %}

<!DOCTYPE html>
<html>
    
    <head>
        <title>Route Development</title>

        <link rel="stylesheet" href="{% static 'HomePage/colors.css' %}">
        <link rel="stylesheet" href="{% static 'RouteDev/RouteDevHome/RouteDevHome.css' %}">
        
    </head>
    
    <body>

        <div id="all-window">
            <div id="header">
                <div id="header-title">
                    <h1>ANALYZE NEW ROUTES</h1>
                </div>
                <div id="header-info">
                    <h3>FIND NEW ROUTES AND THEIR FEASIBILITY & PROFITABILITY VIA THESE 3 STEPS</h3>
                </div>
            </div>
            <div id="icons">
                <div class="icon">
                    <div class="icon-img">
                        <img src="{% static 'RouteDev/RouteDev_Pics/CitySelection.png' %}" alt="City Selection">
                    </div>
                    <div class="icon-text">
                        <div>
                            <h1>CITY SELECTION</h1>
                        </div>
                        <div>
                            <h3>CHOOSE CITIES WITH VERY HIGH GROWTH POTENTIAL IN AIR TRAFFIC DEMAND</h3>
                        </div>
                    </div>
                </div>
                <div class="icon">
                    <div class="icon-text">
                        <div>
                            <h1>ROUTE SELECTION</h1>
                        </div>
                        <div>
                            <h3>INTEGRATE THE CITY INTO YOUR AIRLINE'S NETWORK BY CONNECTING IT TO AN AIRPORT</h3>
                        </div>
                    </div>
                    <div class="icon-img">
                        <img src="{% static 'RouteDev/RouteDev_Pics/RouteSelection.png' %}" alt="Route Selection">
                    </div>
                </div>
                <div class="icon">
                    <div class="icon-img">
                        <img src="{% static 'RouteDev/RouteDev_Pics/CostResourceAnalysis.png' %}" alt="Cost & Resource Analysis">
                    </div>
                    <div class="icon-text">
                        <div>
                            <h1>COST & RESOURCE ANALYSIS</h1>
                        </div>
                        <div>
                            <h3>TWEAK PARAMETERS TO CHECK FEASIBILITY & PROFITABILITY OF NEW ROUTE</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div id="proceed">
                <div id="proceed-button">
                    <a href="{% url 'RouteDev:CitySelection' %}">
                        <h2>PROCEED</h2>
                    </a>
                </div>
            </div>
        </div>
    
    </body>
</html>